/**
 * @file jettyd.c
 * @brief Top-level init + start, boot sequence per spec section 5.
 *
 * Boot sequence:
 *  1. Hardware init (ESP-IDF boot)
 *  2. NVS init
 *  3. Read provisioning state from NVS
 *  4. WiFi connect (with retry + exponential backoff)
 *  5. If not provisioned: fleet token provisioning flow
 *  6. If provisioned: connect MQTT with device key
 *  7. Register all compiled-in drivers (auto-generated driver_init.c)
 *  8. Publish device manifest (capabilities) to shadow
 *  9. Load JettyScript rules from NVS
 * 10. Start rule VM
 * 11. Start heartbeat timer
 * 12. Subscribe to command, config, firmware topics
 * 13. Enter main loop
 */

#include "jettyd.h"
#include "sdkconfig.h"
#include "jettyd_nvs.h"
#include "jettyd_wifi.h"
#include "jettyd_mqtt.h"
#include "jettyd_provision.h"
#include "jettyd_shadow.h"
#include "jettyd_ota.h"
#include "jettyd_telemetry.h"
#include "jettyd_vm.h"
#include "jettyd_driver.h"
#include "esp_log.h"
#include "esp_system.h"
#include "esp_timer.h"
#include "esp_task_wdt.h"
#include "cJSON.h"
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include <string.h>
#include <stdio.h>

static const char *TAG = "jettyd";

/* Firmware version and device type — set via Kconfig (sdkconfig.defaults) */
#ifdef CONFIG_JETTYD_FIRMWARE_VERSION
const char *JETTYD_FIRMWARE_VERSION = CONFIG_JETTYD_FIRMWARE_VERSION;
#else
const char *JETTYD_FIRMWARE_VERSION = "0.0.0";
#endif

#ifdef CONFIG_JETTYD_DEVICE_TYPE
const char *JETTYD_DEVICE_TYPE = CONFIG_JETTYD_DEVICE_TYPE;
#else
const char *JETTYD_DEVICE_TYPE = "esp32-generic";
#endif

static jettyd_config_t s_config = {0};

/* Auto-generated by build.py — registers all compiled-in drivers */
extern void jettyd_register_drivers(void);

/* ───────────────────────────── Command Handler ────────────────────────────── */

/**
 * @brief Handle incoming commands from the platform.
 *
 * Command format: {"id":"cmd_abc","action":"valve.on","params":{"duration":300},"timeout":30}
 * Response: {"id":"cmd_abc","status":"acked","result":{...}}
 */
static void command_handler(const char *topic, const char *data, int data_len)
{
    ESP_LOGI(TAG, "Received command");

    cJSON *root = cJSON_ParseWithLength(data, data_len);
    if (root == NULL) {
        ESP_LOGE(TAG, "Failed to parse command JSON");
        return;
    }

    cJSON *id_obj = cJSON_GetObjectItem(root, "id");
    cJSON *action_obj = cJSON_GetObjectItem(root, "action");
    cJSON *params_obj = cJSON_GetObjectItem(root, "params");

    const char *cmd_id = cJSON_IsString(id_obj) ? id_obj->valuestring : "unknown";
    const char *action_str = cJSON_IsString(action_obj) ? action_obj->valuestring : "";

    /* Parse "instance.action" */
    const char *dot = strchr(action_str, '.');
    char instance[JETTYD_MAX_INSTANCE_NAME] = {0};
    const char *cmd_action = "";

    if (dot) {
        size_t inst_len = (size_t)(dot - action_str);
        if (inst_len >= sizeof(instance)) inst_len = sizeof(instance) - 1;
        memcpy(instance, action_str, inst_len);
        cmd_action = dot + 1;
    }

    const jettyd_driver_t *drv = jettyd_driver_find(instance);
    const char *status = "failed";
    cJSON *result = cJSON_CreateObject();

    if (drv == NULL) {
        status = "rejected";
        cJSON_AddStringToObject(result, "error", "Unknown device instance");
    } else if (strcmp(cmd_action, "on") == 0) {
        if (drv->switch_on == NULL) {
            status = "rejected";
            cJSON_AddStringToObject(result, "error", "Not switchable");
        } else {
            uint32_t duration_ms = 0;
            if (params_obj) {
                cJSON *dur = cJSON_GetObjectItem(params_obj, "duration");
                if (cJSON_IsNumber(dur)) {
                    duration_ms = (uint32_t)(dur->valueint * 1000);
                }
            }
            esp_err_t err = drv->switch_on(duration_ms);
            if (err == ESP_OK) {
                status = "acked";
                char state_key[48];
                snprintf(state_key, sizeof(state_key), "%s.state", instance);
                cJSON_AddBoolToObject(result, state_key, true);
                if (duration_ms > 0) {
                    uint32_t auto_off_ts = (uint32_t)(time(NULL)) + duration_ms / 1000;
                    cJSON_AddNumberToObject(result, "will_auto_off_at", auto_off_ts);
                }
            }
        }
    } else if (strcmp(cmd_action, "off") == 0) {
        if (drv->switch_off == NULL) {
            status = "rejected";
            cJSON_AddStringToObject(result, "error", "Not switchable");
        } else {
            esp_err_t err = drv->switch_off();
            if (err == ESP_OK) {
                status = "acked";
                char state_key[48];
                snprintf(state_key, sizeof(state_key), "%s.state", instance);
                cJSON_AddBoolToObject(result, state_key, false);
            }
        }
    } else if (strcmp(cmd_action, "read") == 0) {
        if (drv->read == NULL) {
            status = "rejected";
            cJSON_AddStringToObject(result, "error", "Not readable");
        } else {
            for (uint8_t c = 0; c < drv->capability_count; c++) {
                jettyd_value_t val = drv->read(drv->capabilities[c].name);
                if (val.valid) {
                    char key[48];
                    snprintf(key, sizeof(key), "%s.%s", instance, drv->capabilities[c].name);
                    switch (val.type) {
                    case JETTYD_VAL_FLOAT:
                        cJSON_AddNumberToObject(result, key, val.float_val);
                        break;
                    case JETTYD_VAL_INT:
                        cJSON_AddNumberToObject(result, key, val.int_val);
                        break;
                    case JETTYD_VAL_BOOL:
                        cJSON_AddBoolToObject(result, key, val.bool_val);
                        break;
                    case JETTYD_VAL_STRING:
                        cJSON_AddStringToObject(result, key, val.str_val);
                        break;
                    }
                }
            }
            status = "acked";
        }
    } else {
        status = "rejected";
        cJSON_AddStringToObject(result, "error", "Unknown action");
    }

    /* Publish response */
    cJSON *resp = cJSON_CreateObject();
    cJSON_AddStringToObject(resp, "id", cmd_id);
    cJSON_AddStringToObject(resp, "status", status);
    cJSON_AddItemToObject(resp, "result", result);

    char *resp_str = cJSON_PrintUnformatted(resp);
    cJSON_Delete(resp);

    if (resp_str) {
        char resp_topic[JETTYD_MQTT_MAX_TOPIC];
        if (jettyd_mqtt_build_topic(resp_topic, sizeof(resp_topic), "command/response") == ESP_OK) {
            jettyd_mqtt_publish(resp_topic, resp_str, 1, false);
        }
        cJSON_free(resp_str);
    }

    cJSON_Delete(root);
}

/* ───────────────────────────── Public API ─────────────────────────────────── */

const jettyd_config_t *jettyd_get_config(void)
{
    return &s_config;
}

esp_err_t jettyd_init(const jettyd_config_t *config)
{
    if (config == NULL) {
        return ESP_ERR_INVALID_ARG;
    }

    memcpy(&s_config, config, sizeof(jettyd_config_t));
    /* JETTYD_FIRMWARE_VERSION and JETTYD_DEVICE_TYPE are set at compile time
     * via CONFIG_JETTYD_FIRMWARE_VERSION / CONFIG_JETTYD_DEVICE_TYPE (Kconfig).
     * Runtime override via config->firmware_version / config->device_type is ignored. */

    ESP_LOGI(TAG, "═══════════════════════════════════════");
    ESP_LOGI(TAG, "  Jettyd Firmware SDK");
    ESP_LOGI(TAG, "  Device: %s", config->device_type);
    ESP_LOGI(TAG, "  Version: %s", config->firmware_version);
    ESP_LOGI(TAG, "═══════════════════════════════════════");

    /* Step 2: NVS init */
    esp_err_t err = jettyd_nvs_init();
    if (err != ESP_OK) {
        ESP_LOGE(TAG, "NVS init failed");
        return err;
    }

    /* Step 3: Read provisioning state */
    err = jettyd_provision_init();
    if (err != ESP_OK) {
        ESP_LOGE(TAG, "Provision init failed");
        return err;
    }

    /* Initialize subsystems */
    jettyd_driver_registry_init();
    jettyd_shadow_init();
    jettyd_ota_init();
    jettyd_telemetry_init();
    jettyd_vm_init();

    /* WiFi init (does not connect yet) */
    err = jettyd_wifi_init();
    if (err != ESP_OK) {
        ESP_LOGE(TAG, "WiFi init failed");
        return err;
    }

    ESP_LOGI(TAG, "Init complete");
    return ESP_OK;
}

esp_err_t jettyd_start(void)
{
    ESP_LOGI(TAG, "Starting...");

    /* Step 4: WiFi connect */
    esp_err_t err = jettyd_wifi_connect();
    if (err != ESP_OK) {
        ESP_LOGE(TAG, "WiFi connect failed");
        return err;
    }

    /* Configure MQTT */
    const jettyd_provision_state_t *prov = jettyd_provision_get_state();

    jettyd_mqtt_config_t mqtt_cfg = {
        .broker_uri = prov->mqtt_uri,
        .keepalive_sec = s_config.mqtt_keepalive,
        .qos = s_config.mqtt_qos,
        .buffer_on_disconnect = s_config.mqtt_buffer_on_disconnect,
        .max_buffer_size = s_config.mqtt_max_buffer_size,
    };

    if (prov->provisioned) {
        /* Step 6: Connect with device key */
        mqtt_cfg.username = prov->device_id;
        mqtt_cfg.password = prov->device_key;
        mqtt_cfg.client_id = prov->device_id;
    } else {
        /* Step 5: Connect with fleet token for provisioning */
        mqtt_cfg.username = "provision";
        mqtt_cfg.password = prov->fleet_token;
        mqtt_cfg.client_id = "provision";
    }

    err = jettyd_mqtt_init(&mqtt_cfg);
    if (err != ESP_OK) {
        ESP_LOGE(TAG, "MQTT init failed");
        return err;
    }

    err = jettyd_mqtt_connect();
    if (err != ESP_OK) {
        ESP_LOGE(TAG, "MQTT connect failed");
        return err;
    }

    /* Wait for MQTT connection */
    int mqtt_wait = 0;
    while (!jettyd_mqtt_is_connected() && mqtt_wait < 100) {
        vTaskDelay(pdMS_TO_TICKS(100));
        mqtt_wait++;
    }

    if (!jettyd_mqtt_is_connected()) {
        ESP_LOGW(TAG, "MQTT not connected after timeout, continuing...");
    }

    /* Step 5: Provisioning if needed */
    if (!prov->provisioned) {
        err = jettyd_provision_run();
        if (err != ESP_OK) {
            ESP_LOGE(TAG, "Provisioning failed");
            return err;
        }
    }

    /* Step 7: Register compiled-in drivers */
    ESP_LOGI(TAG, "Registering drivers...");
    jettyd_register_drivers();
    ESP_LOGI(TAG, "Registered %d drivers", jettyd_driver_count());

    /* Step 8: Publish device manifest to shadow */
    {
        jettyd_value_t fw_val = {.type = JETTYD_VAL_STRING, .valid = true};
        strncpy(fw_val.str_val, s_config.firmware_version, sizeof(fw_val.str_val) - 1);
        jettyd_shadow_update_system("firmware_version", fw_val);
        jettyd_shadow_publish();
    }

    /* Step 9: Load JettyScript rules from NVS */
    err = jettyd_vm_load_from_nvs();
    if (err != ESP_OK) {
        ESP_LOGW(TAG, "No saved config, running with defaults");
        /* Set up default heartbeat from config */
        if (s_config.default_metrics && s_config.heartbeat_interval_sec > 0) {
            ESP_LOGI(TAG, "Using default heartbeat (interval: %lu sec)",
                     (unsigned long)s_config.heartbeat_interval_sec);
        }
    }

    /* Step 10: Start rule VM */
    jettyd_vm_start();

    /* Step 11: Heartbeat is managed by the VM */

    /* Step 12-14: Subscribe to topics */
    char topic[JETTYD_MQTT_MAX_TOPIC];

    if (jettyd_mqtt_build_topic(topic, sizeof(topic), "command") == ESP_OK) {
        jettyd_mqtt_subscribe(topic, s_config.mqtt_qos, command_handler);
    }

    if (jettyd_mqtt_build_topic(topic, sizeof(topic), "config") == ESP_OK) {
        jettyd_mqtt_subscribe(topic, s_config.mqtt_qos, jettyd_vm_config_handler);
    }

    if (jettyd_mqtt_build_topic(topic, sizeof(topic), "firmware") == ESP_OK) {
        jettyd_mqtt_subscribe(topic, s_config.mqtt_qos, jettyd_ota_mqtt_handler);
    }

    if (jettyd_mqtt_build_topic(topic, sizeof(topic), "shadow/desired") == ESP_OK) {
        jettyd_mqtt_subscribe(topic, s_config.mqtt_qos, jettyd_shadow_desired_handler);
    }

    /* Publish online status */
    jettyd_telemetry_publish_status("online");

    /* Mark OTA as valid (we successfully booted and started) */
    jettyd_ota_mark_valid();

    ESP_LOGI(TAG, "═══════════════════════════════════════");
    ESP_LOGI(TAG, "  Jettyd running");
    ESP_LOGI(TAG, "  Drivers: %d", jettyd_driver_count());
    ESP_LOGI(TAG, "  Rules: %d", jettyd_vm_get_state()->rule_count);
    ESP_LOGI(TAG, "  Heartbeats: %d", jettyd_vm_get_state()->heartbeat_count);
    ESP_LOGI(TAG, "═══════════════════════════════════════");

    /* Step 15: Main loop — watchdog feed + shadow persistence */
    while (1) {
        /* Feed watchdog */
        esp_task_wdt_reset();

        /* Periodically persist shadow */
        jettyd_shadow_persist();

        vTaskDelay(pdMS_TO_TICKS(10000));
    }

    /* Never reached */
    return ESP_OK;
}
