/**
 * @file jettyd.c
 * @brief Top-level init + start, boot sequence per spec section 5.
 *
 * Boot sequence:
 *  1. Hardware init (ESP-IDF boot)
 *  2. NVS init
 *  3. Read provisioning state from NVS
 *  4. WiFi connect (with retry + exponential backoff)
 *  5. If not provisioned: fleet token provisioning flow
 *  6. If provisioned: connect MQTT with device key
 *  7. Register all compiled-in drivers (auto-generated driver_init.c)
 *  8. Publish device manifest (capabilities) to shadow
 *  9. Load JettyScript rules from NVS
 * 10. Start rule VM
 * 11. Start heartbeat timer
 * 12. Subscribe to command, config, firmware topics
 * 13. Enter main loop
 */

#include "jettyd.h"
#include "sdkconfig.h"
#include "jettyd_nvs.h"
#include "jettyd_wifi.h"
#include "jettyd_mqtt.h"
#include "jettyd_provision.h"
#include "jettyd_shadow.h"
#include "jettyd_ota.h"
#include "jettyd_telemetry.h"
#include "jettyd_vm.h"
#include "jettyd_driver.h"
#include "jettyd_manifest.h"
#include "jettyd_mcp.h"
#include "jettyd_wifi_portal.h"
#include "esp_log.h"
#if CONFIG_JETTYD_WIFI_PORTAL && CONFIG_SOC_WIFI_SUPPORTED
#include "driver/gpio.h"
#endif
#include "esp_system.h"
#include "esp_timer.h"
#include <time.h>
#include "cJSON.h"
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include <string.h>
#include <stdio.h>

static const char *TAG = "jettyd";

/* wifi.set reconnect timeout — configurable via Kconfig, with a safe default
 * when the SDK is built without the menuconfig option present. */
#ifndef CONFIG_JETTYD_WIFI_SET_TIMEOUT_MS
#define CONFIG_JETTYD_WIFI_SET_TIMEOUT_MS 30000
#endif

/* Firmware version and device type — set via Kconfig (sdkconfig.defaults) */
#ifdef CONFIG_JETTYD_FIRMWARE_VERSION
const char *JETTYD_FIRMWARE_VERSION = CONFIG_JETTYD_FIRMWARE_VERSION;
#else
const char *JETTYD_FIRMWARE_VERSION = "0.0.0";
#endif

#ifdef CONFIG_JETTYD_DEVICE_TYPE
const char *JETTYD_DEVICE_TYPE = CONFIG_JETTYD_DEVICE_TYPE;
#else
const char *JETTYD_DEVICE_TYPE = "esp32-generic";
#endif

static jettyd_config_t s_config = {0};

/* Auto-generated by build.py — registers all compiled-in drivers */
/* jettyd_register_drivers is declared weak in jettyd.h — user overrides in their main/ component */

/* ───────────────────────────── Command Handler ────────────────────────────── */

/**
 * @brief Handle the `wifi.set` device command.
 *
 * Payload: {"ssid":"<string>","password":"<string>"}. An empty or absent
 * password means an open network. The payload is validated here (so an invalid
 * one is rejected without touching NVS); a valid one is handed to
 * jettyd_wifi_reconfigure(), which performs the NVS write, reconnect, and
 * rollback-on-failure. Because the device necessarily drops MQTT during the
 * switch, the ack produced here is published by the caller once the MQTT
 * session is re-established (buffered on disconnect and flushed on reconnect).
 */
static void handle_wifi_set(const cJSON *payload, const char **status, cJSON *result)
{
    if (payload == NULL || !cJSON_IsObject(payload)) {
        *status = "rejected";
        cJSON_AddStringToObject(result, "error", "payload must be an object");
        return;
    }

    const cJSON *ssid_obj = cJSON_GetObjectItem(payload, "ssid");
    const cJSON *pass_obj = cJSON_GetObjectItem(payload, "password");
    const char *ssid = cJSON_IsString(ssid_obj) ? ssid_obj->valuestring : "";
    const char *password = cJSON_IsString(pass_obj) ? pass_obj->valuestring : "";

    size_t ssid_len = strlen(ssid);
    if (ssid_len == 0) {
        *status = "rejected";
        cJSON_AddStringToObject(result, "error", "ssid is required");
        return;
    }
    if (ssid_len > 32) {
        *status = "rejected";
        cJSON_AddStringToObject(result, "error", "ssid exceeds 32 bytes");
        return;
    }
    if (strlen(password) > 64) {
        *status = "rejected";
        cJSON_AddStringToObject(result, "error", "password exceeds 64 bytes");
        return;
    }

    esp_err_t err = jettyd_wifi_reconfigure(ssid, password,
                                            CONFIG_JETTYD_WIFI_SET_TIMEOUT_MS);
    if (err == ESP_OK) {
        *status = "acked";
        cJSON_AddStringToObject(result, "wifi.ssid", ssid);
        cJSON_AddBoolToObject(result, "connected", true);
    } else if (err == ESP_ERR_INVALID_ARG || err == ESP_ERR_INVALID_SIZE) {
        *status = "rejected";
        cJSON_AddStringToObject(result, "error", "invalid wifi credentials");
    } else if (err == ESP_ERR_NOT_SUPPORTED) {
        *status = "rejected";
        cJSON_AddStringToObject(result, "error", "WiFi is not supported on this device");
    } else {
        *status = "failed";
        cJSON_AddStringToObject(result, "error",
                                "could not join new network; rolled back to previous WiFi");
    }
}

/**
 * @brief Handle incoming commands from the platform.
 *
 * Command format: {"id":"cmd_abc","action":"valve.on","params":{"duration":300},"timeout":30}
 * The platform may equivalently send command_type/payload; both spellings are
 * accepted here. Response: {"id":"cmd_abc","status":"acked","result":{...}}
 */
static void command_handler(const char *topic, const char *data, int data_len)
{
    cJSON *root = cJSON_ParseWithLength(data, data_len);
    if (root == NULL) {
        ESP_LOGE(TAG, "Failed to parse command JSON");
        return;
    }

    cJSON *id_obj = cJSON_GetObjectItem(root, "id");
    /* Accept both the action/params and command_type/payload spellings. */
    cJSON *action_obj = cJSON_GetObjectItem(root, "action");
    if (!cJSON_IsString(action_obj)) {
        action_obj = cJSON_GetObjectItem(root, "command_type");
    }
    cJSON *params_obj = cJSON_GetObjectItem(root, "params");
    if (params_obj == NULL) {
        params_obj = cJSON_GetObjectItem(root, "payload");
    }

    const char *cmd_id = cJSON_IsString(id_obj) ? id_obj->valuestring : "unknown";
    const char *action_str = cJSON_IsString(action_obj) ? action_obj->valuestring : "";

    ESP_LOGI(TAG, "Command id=%s action=%s", cmd_id, action_str);

    /* Parse "instance.action" */
    const char *dot = strchr(action_str, '.');
    char instance[JETTYD_MAX_INSTANCE_NAME] = {0};
    const char *cmd_action = "";

    if (dot) {
        size_t inst_len = (size_t)(dot - action_str);
        if (inst_len >= sizeof(instance)) inst_len = sizeof(instance) - 1;
        memcpy(instance, action_str, inst_len);
        cmd_action = dot + 1;
    }

    const jettyd_driver_t *drv = jettyd_driver_find(instance);
    const char *status = "rejected";
    cJSON *result = cJSON_CreateObject();

    /* wifi.set — runtime WiFi credential update with rollback (FLU-163).
     * Handled before driver dispatch since "wifi" is not a driver instance. */
    if (strcmp(action_str, "wifi.set") == 0) {
        handle_wifi_set(params_obj, &status, result);
    /* System commands (no instance prefix, e.g. "reboot", "ping") */
    } else if (dot == NULL || instance[0] == '\0') {
        if (strcmp(action_str, "reboot") == 0) {
            /* ACK first, then reboot after a brief MQTT flush delay */
            status = "acked";
            cJSON_AddStringToObject(result, "message", "Rebooting...");
            cJSON *resp = cJSON_CreateObject();
            cJSON_AddStringToObject(resp, "id", cmd_id);
            cJSON_AddStringToObject(resp, "status", status);
            cJSON_AddItemToObject(resp, "result", result);
            char *resp_str = cJSON_PrintUnformatted(resp);
            if (resp_str) {
                char resp_topic[JETTYD_MQTT_MAX_TOPIC];
                if (jettyd_mqtt_build_topic(resp_topic, sizeof(resp_topic), "command/response") == ESP_OK) {
                    jettyd_mqtt_publish(resp_topic, resp_str, 1, false);
                }
                free(resp_str);
            }
            cJSON_Delete(resp);
            ESP_LOGI(TAG, "Rebooting via command...");
            vTaskDelay(pdMS_TO_TICKS(300));
            esp_restart();
            return;
        } else if (strcmp(action_str, "ping") == 0) {
            status = "acked";
            cJSON_AddStringToObject(result, "message", "pong");
        } else {
            cJSON_AddStringToObject(result, "error", "Unknown system command");
        }
    } else if (drv == NULL) {
        cJSON_AddStringToObject(result, "error", "Unknown device instance");
    } else if (strcmp(cmd_action, "on") == 0) {
        if (drv->switch_on == NULL) {
            status = "rejected";
            cJSON_AddStringToObject(result, "error", "Not switchable");
        } else {
            uint32_t duration_ms = 0;
            if (params_obj) {
                cJSON *dur = cJSON_GetObjectItem(params_obj, "duration");
                if (cJSON_IsNumber(dur)) {
                    duration_ms = (uint32_t)(dur->valueint * 1000);
                }
                /* Apply any extra writable params (e.g. freq) before switching on */
                if (drv->write) {
                    for (uint8_t c = 0; c < drv->capability_count; c++) {
                        const char *cap = drv->capabilities[c].name;
                        if (drv->capabilities[c].type != JETTYD_CAP_WRITABLE) continue;
                        cJSON *param = cJSON_GetObjectItem(params_obj, cap);
                        if (!param) continue;
                        jettyd_value_t val = {0};
                        if (cJSON_IsNumber(param)) {
                            if (drv->capabilities[c].value_type == JETTYD_VAL_INT) {
                                val.type = JETTYD_VAL_INT; val.int_val = (int32_t)param->valueint;
                            } else {
                                val.type = JETTYD_VAL_FLOAT; val.float_val = (float)param->valuedouble;
                            }
                            val.valid = true;
                        } else if (cJSON_IsBool(param)) {
                            val.type = JETTYD_VAL_BOOL; val.bool_val = cJSON_IsTrue(param);
                            val.valid = true;
                        } else if (cJSON_IsString(param)) {
                            val.type = JETTYD_VAL_STRING;
                            strncpy(val.str_val, param->valuestring, sizeof(val.str_val) - 1);
                            val.valid = true;
                        }
                        if (val.valid) drv->write(cap, val);
                    }
                }
            }
            esp_err_t err = drv->switch_on(duration_ms);
            if (err == ESP_OK) {
                status = "acked";
                char state_key[48];
                snprintf(state_key, sizeof(state_key), "%s.state", instance);
                cJSON_AddBoolToObject(result, state_key, true);
                if (duration_ms > 0) {
                    uint32_t auto_off_ts = (uint32_t)(time(NULL)) + duration_ms / 1000;
                    cJSON_AddNumberToObject(result, "will_auto_off_at", auto_off_ts);
                }
            }
        }
    } else if (strcmp(cmd_action, "off") == 0) {
        if (drv->switch_off == NULL) {
            status = "rejected";
            cJSON_AddStringToObject(result, "error", "Not switchable");
        } else {
            esp_err_t err = drv->switch_off();
            if (err == ESP_OK) {
                status = "acked";
                char state_key[48];
                snprintf(state_key, sizeof(state_key), "%s.state", instance);
                cJSON_AddBoolToObject(result, state_key, false);
            }
        }
    } else if (strcmp(cmd_action, "read") == 0) {
        if (drv->read == NULL) {
            status = "rejected";
            cJSON_AddStringToObject(result, "error", "Not readable");
        } else {
            for (uint8_t c = 0; c < drv->capability_count; c++) {
                jettyd_value_t val = drv->read(drv->capabilities[c].name);
                if (val.valid) {
                    char key[48];
                    snprintf(key, sizeof(key), "%s.%s", instance, drv->capabilities[c].name);
                    switch (val.type) {
                    case JETTYD_VAL_FLOAT:
                        cJSON_AddNumberToObject(result, key, val.float_val);
                        break;
                    case JETTYD_VAL_INT:
                        cJSON_AddNumberToObject(result, key, val.int_val);
                        break;
                    case JETTYD_VAL_BOOL:
                        cJSON_AddBoolToObject(result, key, val.bool_val);
                        break;
                    case JETTYD_VAL_STRING:
                        cJSON_AddStringToObject(result, key, val.str_val);
                        break;
                    }
                }
            }
            status = "acked";
        }
    } else if (strcmp(cmd_action, "set") == 0) {
        if (drv->write == NULL) {
            status = "rejected";
            cJSON_AddStringToObject(result, "error", "Not writable");
        } else if (params_obj == NULL || !cJSON_IsObject(params_obj)) {
            status = "rejected";
            cJSON_AddStringToObject(result, "error", "params must be an object");
        } else {
            bool any_ok = false;
            for (uint8_t c = 0; c < drv->capability_count; c++) {
                const char *cap = drv->capabilities[c].name;
                if (drv->capabilities[c].type != JETTYD_CAP_WRITABLE) continue;
                cJSON *param = cJSON_GetObjectItem(params_obj, cap);
                if (param == NULL) continue;
                jettyd_value_t val = {0};
                if (cJSON_IsNumber(param)) {
                    if (drv->capabilities[c].value_type == JETTYD_VAL_INT) {
                        val.type = JETTYD_VAL_INT;
                        val.int_val = (int32_t)param->valueint;
                    } else {
                        val.type = JETTYD_VAL_FLOAT;
                        val.float_val = (float)param->valuedouble;
                    }
                    val.valid = true;
                } else if (cJSON_IsBool(param)) {
                    val.type = JETTYD_VAL_BOOL;
                    val.bool_val = cJSON_IsTrue(param);
                    val.valid = true;
                } else if (cJSON_IsString(param)) {
                    val.type = JETTYD_VAL_STRING;
                    strncpy(val.str_val, param->valuestring, sizeof(val.str_val) - 1);
                    val.str_val[sizeof(val.str_val) - 1] = '\0';
                    val.valid = true;
                }
                if (val.valid && drv->write(cap, val) == ESP_OK) {
                    char key[48];
                    snprintf(key, sizeof(key), "%s.%s", instance, cap);
                    if (val.type == JETTYD_VAL_INT)        cJSON_AddNumberToObject(result, key, val.int_val);
                    else if (val.type == JETTYD_VAL_FLOAT)  cJSON_AddNumberToObject(result, key, val.float_val);
                    else if (val.type == JETTYD_VAL_BOOL)   cJSON_AddBoolToObject(result, key, val.bool_val);
                    else if (val.type == JETTYD_VAL_STRING) cJSON_AddStringToObject(result, key, val.str_val);
                    any_ok = true;
                }
            }
            status = any_ok ? "acked" : "rejected";
            if (!any_ok) cJSON_AddStringToObject(result, "error", "No writable capability matched params");
        }
    } else if (drv->command != NULL) {
        /* Fall through to the driver's custom command hook (e.g. servo "rotate") */
        char *params_str = params_obj ? cJSON_PrintUnformatted(params_obj) : NULL;
        esp_err_t err = drv->command(cmd_action, params_str);
        if (params_str) {
            cJSON_free(params_str);
        }
        if (err == ESP_OK) {
            status = "acked";
        } else if (err == ESP_ERR_NOT_SUPPORTED) {
            cJSON_AddStringToObject(result, "error", "Unknown action");
        } else {
            status = "failed";
            cJSON_AddStringToObject(result, "error", "Command execution failed");
        }
    } else {
        status = "rejected";
        cJSON_AddStringToObject(result, "error", "Unknown action");
    }

    /* Publish response */
    cJSON *resp = cJSON_CreateObject();
    cJSON_AddStringToObject(resp, "id", cmd_id);
    cJSON_AddStringToObject(resp, "status", status);
    cJSON_AddItemToObject(resp, "result", result);

    char *resp_str = cJSON_PrintUnformatted(resp);
    cJSON_Delete(resp);

    if (resp_str) {
        char resp_topic[JETTYD_MQTT_MAX_TOPIC];
        if (jettyd_mqtt_build_topic(resp_topic, sizeof(resp_topic), "command/response") == ESP_OK) {
            jettyd_mqtt_publish(resp_topic, resp_str, 1, false);
        }
        cJSON_free(resp_str);
    }

    cJSON_Delete(root);
}

/* ───────────────────────────── Public API ─────────────────────────────────── */

const jettyd_config_t *jettyd_get_config(void)
{
    return &s_config;
}



esp_err_t jettyd_init(const jettyd_config_t *config)
{
    if (config == NULL) {
        return ESP_ERR_INVALID_ARG;
    }

    memcpy(&s_config, config, sizeof(jettyd_config_t));
    /* JETTYD_FIRMWARE_VERSION and JETTYD_DEVICE_TYPE are set at compile time
     * via CONFIG_JETTYD_FIRMWARE_VERSION / CONFIG_JETTYD_DEVICE_TYPE (Kconfig).
     * Runtime override via config->firmware_version / config->device_type is ignored. */

    ESP_LOGI(TAG, "═══════════════════════════════════════");
    ESP_LOGI(TAG, "  Jettyd Firmware SDK");
    ESP_LOGI(TAG, "  Device: %s", config->device_type);
    ESP_LOGI(TAG, "  Version: %s", config->firmware_version);
    ESP_LOGI(TAG, "═══════════════════════════════════════");

    /* Step 2: NVS init */
    esp_err_t err = jettyd_nvs_init();
    if (err != ESP_OK) {
        ESP_LOGE(TAG, "NVS init failed");
        return err;
    }

    /* Step 3: Read provisioning state */
    err = jettyd_provision_init();
    if (err != ESP_OK) {
        ESP_LOGE(TAG, "Provision init failed");
        return err;
    }

    /* Initialize subsystems */
    jettyd_driver_registry_init();
    jettyd_shadow_init();
    jettyd_ota_init();
    jettyd_telemetry_init();
    jettyd_vm_init();

    /* WiFi init (does not connect yet) */
    err = jettyd_wifi_init();
    if (err != ESP_OK) {
        ESP_LOGE(TAG, "WiFi init failed");
        return err;
    }

    ESP_LOGI(TAG, "Init complete");
    return ESP_OK;
}

esp_err_t jettyd_start(void)
{
    ESP_LOGI(TAG, "Starting...");

    /* Step 4: WiFi connect */
    esp_err_t err = jettyd_wifi_connect();
    if (err != ESP_OK) {
        ESP_LOGE(TAG, "WiFi connect failed (%d consecutive failures)",
                 jettyd_wifi_get_fail_count());

#if CONFIG_JETTYD_WIFI_PORTAL && CONFIG_SOC_WIFI_SUPPORTED
        {
            const jettyd_provision_state_t *prov = jettyd_provision_get_state();

            /* Arming condition (a): no SSID in NVS → fresh device */
            bool no_ssid = (prov == NULL || prov->wifi_ssid[0] == '\0');

            /* Arming condition (b): within boot window */
            int64_t elapsed_us = esp_timer_get_time();
            bool in_boot_window = (elapsed_us <
                (int64_t)CONFIG_JETTYD_WIFI_PORTAL_BOOT_WINDOW_S * 1000000LL);

            /* Arming condition (c): boot/user button held (GPIO0, active-low) */
            bool button_held = (gpio_get_level(0) == 0);

            bool armed   = jettyd_portal_is_armed(no_ssid, in_boot_window, button_held);
            bool trigger = jettyd_portal_should_trigger(
                jettyd_wifi_get_fail_count(),
                CONFIG_JETTYD_WIFI_PORTAL_FAIL_THRESHOLD,
                armed);

            if (trigger) {
                ESP_LOGI(TAG, "Portal trigger: armed=%d (no_ssid=%d boot_window=%d btn=%d)",
                         (int)armed, (int)no_ssid, (int)in_boot_window, (int)button_held);
                jettyd_portal_start(prov ? prov->device_id : "");
                /* Never reached — portal always reboots */
            } else {
                ESP_LOGW(TAG, "WiFi failed but portal not triggered (armed=%d)", (int)armed);
            }
        }
#endif /* CONFIG_JETTYD_WIFI_PORTAL && CONFIG_SOC_WIFI_SUPPORTED */

        return err;
    }

    /* Configure MQTT */
    const jettyd_provision_state_t *prov = jettyd_provision_get_state();

    jettyd_mqtt_config_t mqtt_cfg = {
        .broker_uri = prov->mqtt_uri,
        .keepalive_sec = s_config.mqtt_keepalive,
        .qos = s_config.mqtt_qos,
        .buffer_on_disconnect = s_config.mqtt_buffer_on_disconnect,
        .max_buffer_size = s_config.mqtt_max_buffer_size,
    };

    if (prov->provisioned) {
        /* Step 6: Connect with device key */
        mqtt_cfg.username = prov->device_id;
        mqtt_cfg.password = prov->device_key;
        mqtt_cfg.client_id = prov->device_id;
    } else {
        /* Step 5: Connect with fleet token for provisioning */
        mqtt_cfg.username = "provision";
        mqtt_cfg.password = prov->fleet_token;
        mqtt_cfg.client_id = "provision";
    }

    err = jettyd_mqtt_init(&mqtt_cfg);
    if (err != ESP_OK) {
        ESP_LOGE(TAG, "MQTT init failed");
        return err;
    }

    err = jettyd_mqtt_connect();
    if (err != ESP_OK) {
        ESP_LOGE(TAG, "MQTT connect failed");
        return err;
    }

    /* Wait for MQTT connection */
    int mqtt_wait = 0;
    while (!jettyd_mqtt_is_connected() && mqtt_wait < 100) {
        vTaskDelay(pdMS_TO_TICKS(100));
        mqtt_wait++;
    }

    if (!jettyd_mqtt_is_connected()) {
        ESP_LOGW(TAG, "MQTT not connected after timeout, continuing...");
    }

    /* Step 5: Provisioning if needed */
    if (!prov->provisioned) {
        err = jettyd_provision_run();
        if (err != ESP_OK) {
            ESP_LOGE(TAG, "Provisioning failed");
            return err;
        }
    }

    /* Step 7: Register compiled-in drivers.
     * jettyd_register_drivers() is called by the user from main.c
     * BEFORE jettyd_start(), so drivers are already registered here. */
    ESP_LOGI(TAG, "Drivers registered: %d", jettyd_driver_count());

    /* Step 8: Publish device manifest to shadow and to the dedicated manifest topic */
    {
        jettyd_value_t fw_val = {.type = JETTYD_VAL_STRING, .valid = true};
        strlcpy(fw_val.str_val, s_config.firmware_version, sizeof(fw_val.str_val));
        jettyd_shadow_update_system("firmware_version", fw_val);
        jettyd_shadow_publish();
        /* Publish retained driver capability manifest (FLU-113) */
        jettyd_publish_manifest();
    }

    /* Step 9: Load JettyScript rules from NVS */
    err = jettyd_vm_load_from_nvs();
    if (err != ESP_OK) {
        ESP_LOGW(TAG, "No saved config, running with defaults");
        /* Set up default heartbeat from config */
        if (s_config.default_metrics && s_config.heartbeat_interval_sec > 0) {
            ESP_LOGI(TAG, "Using default heartbeat (interval: %lu sec)",
                     (unsigned long)s_config.heartbeat_interval_sec);
        }
    }

    /* Step 10: Start rule VM */
    jettyd_vm_start();

    /* Step 11: Heartbeat is managed by the VM */

    /* Step 12-14: Subscribe to topics */
    char topic[JETTYD_MQTT_MAX_TOPIC];

    if (jettyd_mqtt_build_topic(topic, sizeof(topic), "command") == ESP_OK) {
        jettyd_mqtt_subscribe(topic, s_config.mqtt_qos, command_handler);
    }

    if (jettyd_mqtt_build_topic(topic, sizeof(topic), "config") == ESP_OK) {
        jettyd_mqtt_subscribe(topic, s_config.mqtt_qos, jettyd_vm_config_handler);
    }

    if (jettyd_mqtt_build_topic(topic, sizeof(topic), "firmware") == ESP_OK) {
        jettyd_mqtt_subscribe(topic, s_config.mqtt_qos, jettyd_ota_mqtt_handler);
    }

    if (jettyd_mqtt_build_topic(topic, sizeof(topic), "shadow/desired") == ESP_OK) {
        jettyd_mqtt_subscribe(topic, s_config.mqtt_qos, jettyd_shadow_desired_handler);
    }

    /* Subscribe to mcp/call topic for device-side tool dispatch (FLU-137) */
    jettyd_mcp_init();

    /* Publish online status */
    jettyd_telemetry_publish_status("online");

    /* Mark OTA as valid (we successfully booted and started) */
    jettyd_ota_mark_valid();

    ESP_LOGI(TAG, "═══════════════════════════════════════");
    ESP_LOGI(TAG, "  Jettyd running");
    ESP_LOGI(TAG, "  Drivers: %d", jettyd_driver_count());
    ESP_LOGI(TAG, "  Rules: %d", jettyd_vm_get_state()->rule_count);
    ESP_LOGI(TAG, "  Heartbeats: %d", jettyd_vm_get_state()->heartbeat_count);
    ESP_LOGI(TAG, "═══════════════════════════════════════");

    /* Step 15: Main loop — shadow persistence */
    while (1) {

        /* Periodically persist shadow */
        jettyd_shadow_persist();

        vTaskDelay(pdMS_TO_TICKS(10000));
    }

    /* Never reached */
    return ESP_OK;
}

/* jettyd_register_drivers() is defined in the user's main/driver_registry.c
 * (auto-generated by build.py from device.yaml) and called explicitly from
 * main.c before jettyd_start(). No SDK stub — no linker ambiguity. */

