#!/usr/bin/env python3
"""
Jettyd Firmware Build Tool

Reads device.yaml, generates driver_init.c and driver_manifest.h,
then invokes idf.py build.

Usage:
    python tools/build.py --device soil-moisture-v1 --target esp32s3
"""

import argparse
import os
import subprocess
import sys
import textwrap
from pathlib import Path

import yaml


FIRMWARE_ROOT = Path(__file__).parent.parent.resolve()
DEVICES_DIR = FIRMWARE_ROOT / "devices"
DRIVERS_DIR = FIRMWARE_ROOT / "drivers"


def load_device_yaml(device_name: str) -> dict:
    """Load and validate device.yaml."""
    device_dir = DEVICES_DIR / device_name
    yaml_path = device_dir / "device.yaml"

    if not yaml_path.exists():
        print(f"Error: {yaml_path} not found")
        sys.exit(1)

    with open(yaml_path) as f:
        config = yaml.safe_load(f)

    required = ["name", "version", "target", "drivers"]
    for key in required:
        if key not in config:
            print(f"Error: device.yaml missing required key: {key}")
            sys.exit(1)

    return config


def load_driver_yaml(driver_name: str) -> dict:
    """Load driver.yaml for dependency resolution."""
    driver_dir = DRIVERS_DIR / driver_name
    yaml_path = driver_dir / "driver.yaml"

    if not yaml_path.exists():
        print(f"Warning: {yaml_path} not found, skipping metadata")
        return {}

    with open(yaml_path) as f:
        return yaml.safe_load(f)


def generate_driver_init_c(config: dict, output_path: Path):
    """
    Generate driver_init.c — calls each driver's register function
    with the config from device.yaml.
    """
    drivers = config.get("drivers", [])

    includes = set()
    registrations = []

    for drv in drivers:
        name = drv["name"]
        instance = drv["instance"]
        drv_config = drv.get("config", {})

        includes.add(f'#include "{name}.h"')

        # Build the config struct initialization
        if name == "soil_moisture":
            cfg_init = _soil_moisture_config(drv_config)
            cfg_type = "soil_moisture_config_t"
        elif name == "dht22":
            cfg_init = _dht22_config(drv_config)
            cfg_type = "dht22_config_t"
        elif name == "ds18b20":
            cfg_init = _ds18b20_config(drv_config)
            cfg_type = "ds18b20_config_t"
        elif name == "relay":
            cfg_init = _relay_config(drv_config)
            cfg_type = "relay_config_t"
        else:
            print(f"Warning: Unknown driver '{name}', generating generic config")
            cfg_init = "{0}"
            cfg_type = "void"

        var_name = f"cfg_{instance}"
        registrations.append({
            "name": name,
            "instance": instance,
            "cfg_type": cfg_type,
            "cfg_var": var_name,
            "cfg_init": cfg_init,
        })

    lines = [
        "/* Auto-generated by tools/build.py — do not edit */",
        "",
        '#include "jettyd_driver.h"',
    ]
    for inc in sorted(includes):
        lines.append(inc)

    lines.append("")
    lines.append("void jettyd_register_drivers(void)")
    lines.append("{")

    for reg in registrations:
        lines.append(f"    /* Driver: {reg['name']} instance: {reg['instance']} */")
        lines.append(f"    static {reg['cfg_type']} {reg['cfg_var']} = {reg['cfg_init']};")
        lines.append(f'    {reg["name"]}_register("{reg["instance"]}", &{reg["cfg_var"]});')
        lines.append("")

    lines.append("}")
    lines.append("")

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(lines))
    print(f"Generated: {output_path}")


def generate_driver_manifest_h(config: dict, output_path: Path):
    """
    Generate driver_manifest.h — compile-time constants from device.yaml.
    """
    name = config["name"]
    version = config["version"]
    defaults = config.get("defaults", {})
    mqtt = config.get("mqtt", {})
    power = config.get("power", {})
    hw = config.get("hardware", {})

    heartbeat = defaults.get("heartbeat_interval", 60)
    metrics = defaults.get("report_metrics", [])
    keepalive = mqtt.get("keepalive", 60)
    qos = mqtt.get("qos", 1)
    buffer = mqtt.get("buffer_on_disconnect", True)
    max_buffer = mqtt.get("max_buffer_size", 50)
    deep_sleep = power.get("deep_sleep", False)
    sleep_dur = power.get("sleep_duration", 0) or 0
    has_battery = hw.get("has_battery", False)
    bat_pin = hw.get("battery_adc_pin", -1)
    bat_div = hw.get("battery_voltage_divider", 1.0)
    led_pin = hw.get("status_led_pin", -1)

    # Build metrics array
    metrics_entries = ", ".join(f'"{m}"' for m in metrics)

    lines = [
        "/* Auto-generated by tools/build.py — do not edit */",
        "",
        "#ifndef DRIVER_MANIFEST_H",
        "#define DRIVER_MANIFEST_H",
        "",
        f'#define JETTYD_MANIFEST_DEVICE_TYPE      "{name}"',
        f'#define JETTYD_MANIFEST_FIRMWARE_VERSION  "{version}"',
        f"#define JETTYD_MANIFEST_HEARTBEAT_INTERVAL {heartbeat}",
        f"#define JETTYD_MANIFEST_MQTT_KEEPALIVE    {keepalive}",
        f"#define JETTYD_MANIFEST_MQTT_QOS          {qos}",
        f"#define JETTYD_MANIFEST_MQTT_BUFFER       {'true' if buffer else 'false'}",
        f"#define JETTYD_MANIFEST_MQTT_MAX_BUFFER   {max_buffer}",
        f"#define JETTYD_MANIFEST_DEEP_SLEEP        {'true' if deep_sleep else 'false'}",
        f"#define JETTYD_MANIFEST_SLEEP_DURATION    {sleep_dur}",
        f"#define JETTYD_MANIFEST_HAS_BATTERY       {'true' if has_battery else 'false'}",
        f"#define JETTYD_MANIFEST_BATTERY_ADC_PIN   {bat_pin if bat_pin is not None else -1}",
        f"#define JETTYD_MANIFEST_BATTERY_DIVIDER   {bat_div}f",
        f"#define JETTYD_MANIFEST_STATUS_LED_PIN    {led_pin if led_pin is not None else -1}",
        "",
        f"static const char *JETTYD_MANIFEST_DEFAULT_METRICS[] = {{{metrics_entries}, NULL}};",
        "",
        f"#define JETTYD_MANIFEST_DRIVER_COUNT      {len(config.get('drivers', []))}",
        "",
        "#endif /* DRIVER_MANIFEST_H */",
        "",
    ]

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(lines))
    print(f"Generated: {output_path}")


# ─── Driver config struct generators ──────────────────────────────────────────

def _soil_moisture_config(cfg: dict) -> str:
    pin = cfg.get("pin", 34)
    typ = cfg.get("type", "capacitive")
    dry = cfg.get("dry_value", 4095)
    wet = cfg.get("wet_value", 1200)
    unit = cfg.get("unit", "%")
    return (
        f'{{\n'
        f'        .pin = {pin},\n'
        f'        .type = "{typ}",\n'
        f'        .dry_value = {dry},\n'
        f'        .wet_value = {wet},\n'
        f'        .unit = "{unit}",\n'
        f'    }}'
    )


def _dht22_config(cfg: dict) -> str:
    pin = cfg.get("pin", 4)
    return f'{{\n        .pin = {pin},\n    }}'


def _ds18b20_config(cfg: dict) -> str:
    pin = cfg.get("pin", 5)
    res = cfg.get("resolution", 12)
    return (
        f'{{\n'
        f'        .pin = {pin},\n'
        f'        .resolution = {res},\n'
        f'    }}'
    )


def _relay_config(cfg: dict) -> str:
    pin = cfg.get("pin", 25)
    active_high = "true" if cfg.get("active_high", True) else "false"
    default_on = "true" if cfg.get("default_state", "off") == "on" else "false"
    max_dur = cfg.get("max_on_duration", 1800)
    return (
        f'{{\n'
        f'        .pin = {pin},\n'
        f'        .active_high = {active_high},\n'
        f'        .default_state_on = {default_on},\n'
        f'        .max_on_duration = {max_dur},\n'
        f'    }}'
    )


# ─── Main ─────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(description="Jettyd Firmware Build Tool")
    parser.add_argument("--device", required=True, help="Device name (e.g., soil-moisture-v1)")
    parser.add_argument("--target", help="ESP target (e.g., esp32s3). Overrides device.yaml.")
    parser.add_argument("--generate-only", action="store_true",
                        help="Only generate files, don't build")
    args = parser.parse_args()

    config = load_device_yaml(args.device)
    target = args.target or config.get("target", "esp32s3")

    device_dir = DEVICES_DIR / args.device
    build_dir = device_dir / "build"

    print(f"Building: {config['name']} v{config['version']} for {target}")
    print(f"Drivers: {', '.join(d['name'] + '(' + d['instance'] + ')' for d in config['drivers'])}")

    # Resolve driver dependencies
    esp_components = set()
    for drv in config["drivers"]:
        drv_meta = load_driver_yaml(drv["name"])
        for comp in drv_meta.get("esp_idf_components", []):
            esp_components.add(comp)

        # Validate target compatibility
        compat = drv_meta.get("compatible_targets", [])
        if compat and target not in compat:
            print(f"Warning: Driver '{drv['name']}' may not be compatible with {target}")

    print(f"ESP-IDF components: {', '.join(sorted(esp_components))}")

    # Generate driver_init.c
    generate_driver_init_c(config, build_dir / "driver_init.c")

    # Generate driver_manifest.h
    generate_driver_manifest_h(config, build_dir / "driver_manifest.h")

    if args.generate_only:
        print("Generation complete (--generate-only)")
        return

    # Invoke idf.py build
    env = os.environ.copy()
    cmd = [
        "idf.py",
        "--target", target,
        "-B", str(build_dir),
        "-DJETTYD_DEVICE=" + args.device,
        "build",
    ]

    print(f"\nRunning: {' '.join(cmd)}")
    print("─" * 60)

    try:
        result = subprocess.run(cmd, cwd=str(FIRMWARE_ROOT), env=env)
        if result.returncode != 0:
            print(f"\nBuild failed (exit code {result.returncode})")
            sys.exit(result.returncode)
        else:
            print(f"\nBuild successful!")
            print(f"Output: {build_dir / 'firmware.bin'}")
    except FileNotFoundError:
        print("Error: idf.py not found. Is ESP-IDF installed and sourced?")
        print("Run: . $IDF_PATH/export.sh")
        sys.exit(1)


if __name__ == "__main__":
    main()
